version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: prisma_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"
  redis:
    image: "redis:latest"
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: always    
volumes:
  postgres_data:
    driver: local      